apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intune-device-healer.fullname" . }}-env
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- if .Values.rulesConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intune-device-healer.fullname" . }}-rules
data:
  rules.yaml: |
{{ .Files.Get "config/rules.yaml" | indent 4 }}
{{- end }}
